import jsPDF from "jspdf";
import { Download } from "lucide-react";
import { useScanStore } from "@/store/useScanStore";
import { Button } from "@/components/ui/button";

const PDFExportButton = () => {
  const result = useScanStore((s) => s.result);
  const scanType = useScanStore((s) => s.scanType);

  const handleExport = () => {
    if (!result || !scanType) return;

    const doc = new jsPDF();
    const t = new Date(result.timestamp).toLocaleString();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("HRV Detector Report", 20, 25);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated: ${t}`, 20, 35);
    doc.text(`Scan Type: ${scanType.toUpperCase()}`, 20, 42);

    doc.setDrawColor(200);
    doc.line(20, 48, 190, 48);

    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Stress Level", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Value: ${result.stressLevel.toFixed(1)} / 10`, 20, 68);
    doc.text(`Confidence: ${result.stressConfidence}%`, 20, 76);

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Sleep State", 20, 92);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Value: ${result.sleepState.toFixed(1)} / 10`, 20, 100);
    doc.text(`Confidence: ${result.sleepConfidence}%`, 20, 108);

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("This report is generated by HRV Detector for informational purposes only.", 20, 280);

    doc.save(`hrv-report-${scanType}-${Date.now()}.pdf`);
  };

  return (
    <Button
      onClick={handleExport}
      className="gradient-primary text-primary-foreground font-semibold gap-2 px-6 shadow-soft hover:shadow-elevated transition-shadow"
      aria-label="Download PDF report"
    >
      <Download className="h-4 w-4" />
      Download PDF Report
    </Button>
  );
};

export default PDFExportButton;
